### ISSUE TITLE
Setup Kanban Projects

### ISSUE THREAD

**Issue by ichsansandy** [ichsansandy/catalog-of-things-ruby#6]
- https://github.com/ichsansandy/catalog-of-things-ruby/projects/1
- We have 3 members in the project
- Team member 1 @Mofuhidy 
- Team member 2 @AJ193 
- Team member 3 @ichsansandy

**Comment by V-Blaze** [comment]
## Hi @ichsansandy, @Mofuhidy, @AJ193   

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![giphy](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Descriptive issue summary✔
-  Cards assigned to students👋 
-  Group task assigned to all students✔

 ## Required Changes ♻️

- You have done great so far :+1:  However, there are a few requirements you still need to meet.

- [ ] You did great sharing the task between each student, but just as you have done before in your previous group project, the tasks of each student should be divided into comprehensive multiple tasks. currently, the requirement for each student is in one card which isn't conventional, When working on a project as a team, tasks are divided into bits. For each student, take the tasks and divide them into multiple tasks. :+1: :100: :small_airplane: 

- - Screenshot suggestion:
   
![Selection_021](https://github.com/ichsansandy/catalog-of-things-ruby/assets/107632780/6bf7bde9-5ec2-4c08-adce-194da09f671d)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brainconnect93** [comment]
## Status: Approved :heavy_check_mark:

Hi @ichsansandy, @Mofuhidy, & @AJ193, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... It's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Task properly assigned ✔️
- kanban board created ✔️
- Descriptive issues✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
